language: perl
perl:
  - "5.8.1"
#  - "blead"
before_install:
  - git clone git://github.com/charsbar/helpers ~/travis-perl-helpers -b configure_deps
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
  - cpanm -n DBI
  - build-dist
  - cd $BUILD_DIR             # $BUILD_DIR is set by the build-dist command
  - perl -MDBI -e 'print DBI->VERSION, "\n"'
