language: perl
perl:
  - "5.6.2"
  - "5.8.1"
  - "5.8.8"
  - "5.8.8-thr"
  - "5.8.8-mb"
  - "5.8.8-dbg"
  - "5.8.8@moo"
  - "blead"
before_install:
  - git clone git://github.com/charsbar/helpers ~/travis-perl-helpers -b use_perl_explicitly
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
  - cpanm -n DBI
  - build-dist
  - cd $BUILD_DIR             # $BUILD_DIR is set by the build-dist command
  - perl -MDBI -e 'print DBI->VERSION, "\n"'
